"""Pydantic specifications and output models for LLM-generated prompts (PromtEngineering.md §20)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict, List, Optional
from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from promptwright.builder import PromptBuilder


class GeneratedExample(BaseModel):
    """An input/output few-shot example generated by the meta-prompt agent."""
    input_text: str = Field(description="Sample input demonstrating the request")
    output_text: str = Field(description="Sample expected output demonstrating correct formatting and grounding")
    description: Optional[str] = Field(default=None, description="Brief explanation of what this example demonstrates")


class GeneratedPromptSpec(BaseModel):
    """Structured specification of a prompt generated by an AI Prompt Engineer."""

    role: str = Field(
        description="Specific domain role of the model (e.g. 'Senior QA Engineer reviewing user stories'). Avoid decorative roles like 'an expert'."
    )
    goal: str = Field(
        description="Explicit outcome required (e.g. 'produce a complete test-case matrix derived solely from acceptance criteria')."
    )
    context_data: Optional[str] = Field(
        default=None,
        description="Any static background context, system definitions, or authoritative rules needed by the prompt.",
    )
    inputs: Dict[str, str] = Field(
        default_factory=dict,
        description="Dictionary mapping runtime variable names (e.g. 'user_story') to descriptions of what the variable contains.",
    )
    tasks: List[str] = Field(
        description="Decomposed step-by-step operations using precise action verbs (e.g. 'Step 1: Extract...', 'Step 2: Generate...'). Avoid vague verbs like 'handle' or 'process'."
    )
    constraints: List[str] = Field(
        description="Explicit limits, forbidden assumptions, negative prohibitions reframed positively, and safe missing-data behaviors."
    )
    output_format: str = Field(
        description="Deterministic response schema, JSON format description, or markdown table structure."
    )
    examples: List[GeneratedExample] = Field(
        default_factory=list,
        description="1-3 high-quality few-shot examples demonstrating target behavior.",
    )
    verifications: List[str] = Field(
        description="Self-check verification checklist items the model must confirm before returning its output."
    )
    design_decisions: Optional[str] = Field(
        default=None,
        description="Brief rationale behind the chosen role, constraints, formatting, and decomposition.",
    )
    test_cases: List[str] = Field(
        default_factory=list,
        description="5 mental test cases: normal, missing information, ambiguous, boundary case, malformed input.",
    )
    anti_patterns_avoided: List[str] = Field(
        default_factory=list,
        description="List of detected anti-patterns that were explicitly resolved (e.g. vague verbs eliminated).",
    )

    def to_builder(self) -> "PromptBuilder":
        """Convert the generated specification into a live PromptBuilder instance."""
        from promptwright.builder import PromptBuilder

        builder = PromptBuilder()
        builder.role(self.role)
        builder.goal(self.goal)

        if self.context_data:
            builder.context(self.context_data, tag="context")

        if self.inputs:
            builder.inputs(**self.inputs)

        if self.tasks:
            builder.task(*self.tasks)

        if self.constraints:
            builder.constraints(*self.constraints)

        if self.output_format:
            builder.output_format(self.output_format)

        for ex in self.examples:
            builder.example(
                input_data=ex.input_text,
                output_data=ex.output_text,
                description=ex.description,
            )

        if self.verifications:
            builder.verify(*self.verifications)

        return builder

    def to_markdown(self) -> str:
        """Render the generated prompt as clean, copy-paste ready Markdown per §19."""
        parts: List[str] = []

        parts.append("# Role & Goal\n")
        role_text = self.role.strip()
        if not role_text.lower().startswith("you are"):
            role_text = f"You are a {role_text}."
        goal_text = self.goal.strip()
        if not goal_text.lower().startswith("your goal"):
            goal_text = f"Your goal is to {goal_text}."
        parts.append(f"{role_text}\n{goal_text}\n")

        if self.context_data:
            parts.append(f"# Context\n\n<context>\n{self.context_data}\n</context>\n")

        if self.inputs:
            input_lines = ["# Runtime Inputs\n"]
            for var_name, desc in self.inputs.items():
                input_lines.append(f"- `{var_name}`: {desc}")
            parts.append("\n".join(input_lines) + "\n")

        if self.tasks:
            task_lines = ["# Task\n"]
            for t in self.tasks:
                task_lines.append(f"{t}")
            parts.append("\n".join(task_lines) + "\n")

        if self.constraints:
            const_lines = ["# Constraints\n"]
            for c in self.constraints:
                const_lines.append(f"- {c}")
            parts.append("\n".join(const_lines) + "\n")

        if self.output_format:
            parts.append(f"# Output Format\n\n{self.output_format}\n")

        if self.examples:
            parts.append("# Examples\n")
            for idx, ex in enumerate(self.examples, start=1):
                desc_line = f" ({ex.description})" if ex.description else ""
                parts.append(f"### Example {idx}{desc_line}\nInput:\n```\n{ex.input_text}\n```\nOutput:\n```\n{ex.output_text}\n```\n")

        if self.verifications:
            verif_lines = ["# Verification\n\nBefore returning the answer, verify:"]
            for v in self.verifications:
                verif_lines.append(f"- [ ] {v}")
            verif_lines.append("\nIf any requirement is not satisfied, correct the output before returning it.")
            parts.append("\n".join(verif_lines) + "\n")

        return "\n".join(parts)
